import argparse
import csv
import os


METRIC_COLS = ["average", "min", "score_1", "score_2", "score_3"]
DEFAULT_SCORE = 1.0


def _safe_float(value):
    if value is None or value == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def main():
    parser = argparse.ArgumentParser(description="Calculate average scores from evaluation output CSV.")
    parser.add_argument(
        "--input_csv",
        type=str,
        required=True,
        help="The path to the original input CSV file (used to determine total sample count).",
    )
    parser.add_argument(
        "--output_csv",
        type=str,
        required=True,
        help="The path to the evaluation output CSV file (generated by evaluate_*.py).",
    )
    parser.add_argument(
        "--task_type",
        type=str,
        required=True,
        choices=["interpolative_di2v", "implicit_i2v", "tiv2v"],
        help="The task type name.",
    )
    args = parser.parse_args()

    # ---- 1. Read input CSV to get all cases and total count ----
    with open(args.input_csv, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        input_rows = list(reader)
    total_count = len(input_rows)
    print(f"Task type: {args.task_type}")
    print(f"Input CSV: {args.input_csv}")
    print(f"Total samples in input CSV: {total_count}")

    if total_count == 0:
        print("ERROR: Input CSV is empty, nothing to calculate.")
        return

    # Build a list of input keys (by index field)
    input_keys = []
    for idx, row in enumerate(input_rows):
        key = row.get("index", str(idx))
        input_keys.append(key)

    # ---- 2. Read output CSV and build a lookup by index ----
    output_lookup = {}  # key -> {col: float_value}
    if not os.path.exists(args.output_csv):
        print(f"WARNING: Output CSV does not exist: {args.output_csv}")
        print("All samples will be treated as missing (default score = 1.0).")
    else:
        with open(args.output_csv, "r", encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)
            for out_idx, row in enumerate(reader):
                key = row.get("index", str(out_idx))
                results_field = row.get("results", "")
                # Skip rows with ERROR results
                if results_field == "ERROR":
                    continue
                scores = {}
                all_valid = True
                for col in METRIC_COLS:
                    val = _safe_float(row.get(col))
                    if val is not None:
                        scores[col] = val
                    else:
                        all_valid = False
                if all_valid and scores:
                    output_lookup[key] = scores
        print(f"Output CSV: {args.output_csv}")
        print(f"Valid scored samples in output CSV: {len(output_lookup)}")

    # ---- 3. For each input case, collect scores ----
    sums = {col: 0.0 for col in METRIC_COLS}
    missing_count = 0
    missing_indices = []

    for key in input_keys:
        if key in output_lookup:
            for col in METRIC_COLS:
                sums[col] += output_lookup[key][col]
        else:
            # Missing case: use default score and warn
            missing_count += 1
            missing_indices.append(key)
            print(f"WARNING: Sample '{key}' not found or invalid in output CSV, using default score = {DEFAULT_SCORE}")
            for col in METRIC_COLS:
                sums[col] += DEFAULT_SCORE

    # ---- 4. Calculate and print averages ----
    print(f"\n{'='*60}")
    print(f"Total samples: {total_count}")
    print(f"Valid samples from output:   {total_count - missing_count}")
    print(f"Missing samples: {missing_count}")
    if missing_count > 0:
        print(f"WARNING: {missing_count} samples are missing, please check!")
        print(f"Missing indices: {missing_indices}")
    print(f"{'='*60}")

    DISPLAY_NAMES = {
        "average": "AVG",
        "min": "MIN",
        "score_1": "Instruction Following",
        "score_2": "Condition Preserving",
        "score_3": "Overall Visual Quality",
    }

    print(f"\n--- Average Scores [{args.task_type}] ---")
    for col in METRIC_COLS:
        avg = sums[col] / total_count
        display = DISPLAY_NAMES.get(col, col)
        print(f"  {display}: {avg:.4f}")
    print()


if __name__ == "__main__":
    main()
