"""
Step6: Background Extraction Quality Check

This script verifies the quality of background images extracted by step4. For each
entry from step2's output, it sends the original frame and the corresponding
background image to a VLM server to evaluate whether:
  1. All subjects have been correctly removed from the background image.
  2. No new subjects have been introduced.
  3. The background in the extracted image matches the original.

The background images are expected to be stored in the directory produced by step4,
following the naming convention: {videoid}.png
(This path is NOT stored in the input JSONL; it is derived from --background_img_dir
combined with the videoid from each entry.)

Input (--input_json):
    A JSONL file produced by step2. Each line is a JSON object containing:
        - videoid:     unique identifier for the video
        - image_name:  path to the original frame image
        - objects:     dict with "moving_objects" mapping [objectN] -> description
        - overall:     "yes" from step1's self-check
    Only entries with overall == "yes" and non-empty moving_objects are processed.

Input (--background_img_dir):
    The directory containing background images generated by step4.
    Images are expected to be named as: {videoid}.png

Output (--output):
    A JSONL file where each line is a JSON object with the check results,
    including per-entry background check details and usability flags.

Usage:
    python step6.py \\
        --input_json /path/to/step2_output.jsonl \\
        --background_img_dir /path/to/step4_output/ \\
        --output /path/to/step6_result.jsonl \\
        --server_ip vllm_ip \\
        --server_port vllm_port \\
        --model_name "Qwen/Qwen3-VL-235B-A22B-Instruct"
"""

import json
import os
import io
import base64
import argparse
from datetime import datetime

import requests
from PIL import Image
from tqdm import tqdm


# ────────────────────────── prompts ──────────────────────────

# Check if the background image correctly removes all subjects while
# preserving the original background.
PROMPT_CHECK_BACKGROUND = '''
Given the two images, where the second image aims to remove all subjects and keep only the background from the first image.

You need to make the following judgments regarding the content of the second image:
1. The second image removes all subjects and keeps only the background from the first image.
2. The second image does NOT introduce any new subjects compared to the first image.
3. The background in the second image is the same as the background in the first image.

If the second image fully meets the above three requirements, return "yes", otherwise return "no".

### Output Format:
{{"result":"yes/no"}}
'''

VALID_OBJECT_KEYS = {"[object1]", "[object2]", "[object3]"}


# ────────────────────────── utilities ──────────────────────────

def decode_image(path_or_img, max_side=None) -> str:
    """Read an image file (or accept a PIL Image) and return its base64-encoded string."""
    if isinstance(path_or_img, str):
        im = Image.open(path_or_img).convert("RGB")
    else:
        im = path_or_img.convert("RGB")

    if max_side and max_side > 0:
        w, h = im.size
        scale = max(w, h) / float(max_side)
        if scale > 1:
            im = im.resize((int(round(w / scale)), int(round(h / scale))), Image.BICUBIC)

    buffer = io.BytesIO()
    im.save(buffer, format='JPEG', quality=85)
    return base64.b64encode(buffer.getvalue()).decode()


# ────────────────────────── API helpers ──────────────────────────

def _build_two_image_payload(model_name: str, image_b64_1: str, image_b64_2: str,
                             prompt_text: str, max_new_tokens: int) -> dict:
    """Build the VLM API request payload with two images."""
    return {
        "model": model_name,
        "messages": [{
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_b64_1}"}},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_b64_2}"}},
                {"type": "text", "text": prompt_text},
            ]
        }],
        "max_tokens": max_new_tokens,
    }


def send_check_request(url: str, model_name: str, image_b64_1: str, image_b64_2: str,
                       prompt_text: str, max_new_tokens: int, timeout: int = 30):
    """Send a two-image background check request. Returns (success, error_msg, content_dict)."""
    payload = _build_two_image_payload(model_name, image_b64_1, image_b64_2,
                                       prompt_text, max_new_tokens)
    for attempt in range(3):
        try:
            resp = requests.post(url, json=payload, timeout=timeout)
            if resp.status_code == 200:
                content = resp.json()["choices"][0]["message"]["content"]
                if '</think>' in content:
                    content = content.split('</think>')[-1].strip()
                content = json.loads(content)
                if content.get("result", "").lower() in ('yes', 'no'):
                    return True, "", content
            else:
                print(f"HTTP {resp.status_code}: {resp.text}")
                if attempt >= 2:
                    return False, f"HTTP {resp.status_code}: {resp.text}", None
        except Exception as e:
            print(e)
            if attempt >= 2:
                return False, str(e), None
    return False, "", None


def check_background_image(api_url: str, model_name: str, max_new_tokens: int,
                           original_img, background_img_path: str):
    """
    Check the quality of a single background image.

    Args:
        api_url: VLM API endpoint URL.
        model_name: model name for the API.
        max_new_tokens: max tokens for generation.
        original_img: original frame image (PIL Image).
        background_img_path: path to the extracted background image.

    Returns:
        (check_flag, check_result)
        check_flag:  1 = background OK, 0 = background failed, -1 = error.
    """
    imgb64_1 = decode_image(original_img, 640)
    imgb64_2 = decode_image(background_img_path, 640)

    ok, _, result = send_check_request(api_url, model_name, imgb64_1, imgb64_2,
                                       PROMPT_CHECK_BACKGROUND, max_new_tokens)
    if ok:
        check_flag = 1 if result.get('result', 'no').lower() == 'yes' else 0
    else:
        check_flag = -1
        result = {}

    return check_flag, result


# ────────────────────────── data loading ──────────────────────────

def load_input_data(input_json_path: str) -> list:
    """
    Load valid entries from the step2 output JSONL file.

    Only entries with overall == "yes" and valid, non-empty moving_objects are kept.
    """
    items = []
    with open(input_json_path, 'r', encoding='utf8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue

            if entry.get("overall", "").lower() != "yes":
                continue

            image_path = entry.get('image_name', '')
            if not image_path or not os.path.exists(image_path):
                continue

            try:
                objects = entry['objects']['moving_objects']
            except (KeyError, TypeError):
                continue
            if not objects:
                continue
            if not all(k in VALID_OBJECT_KEYS for k in objects.keys()):
                continue

            items.append(entry)

    return items


def load_existing_results(save_path: str) -> set:
    """Load the set of already-processed videoids from the output file to skip them."""
    if not os.path.exists(save_path):
        return set()

    done_ids = set()
    with open(save_path, 'r', encoding='utf8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
                done_ids.add(item["videoid"])
            except (json.JSONDecodeError, KeyError):
                continue
    return done_ids


# ────────────────────────── main processing ──────────────────────────

def process_single_item(entry: dict, api_url: str, model_name: str,
                        max_new_tokens: int, background_img_dir: str):
    """
    Process a single entry: check the extracted background image for quality.

    Returns (result_dict, is_complete):
        result_dict: the entry enriched with check results.
        is_complete: True if the check completed without errors.
    """
    videoid = entry['videoid']
    image_path = entry['image_name']

    bg_img_path = os.path.join(background_img_dir, f"{videoid}.png")

    # Open the original image
    try:
        original_img = Image.open(image_path).convert('RGB')
        original_img.thumbnail((640, 640))
    except Exception:
        print(f'  Error opening original image: {image_path}')
        return None, False

    # Check that the background image exists
    if not os.path.exists(bg_img_path):
        print(f'  Background image not found: {bg_img_path}')
        return None, False

    is_complete = True

    try:
        check_flag, check_result = check_background_image(
            api_url, model_name, max_new_tokens,
            original_img, bg_img_path
        )
        check_result['image'] = bg_img_path

        if check_flag == -1:
            is_complete = False

        now_str = datetime.now().strftime("%H:%M:%S")
        passed = "yes" if check_flag == 1 else "no"
        print(f'  {now_str}: background check -> {passed}')

    except Exception as e:
        print(f'  Error checking {bg_img_path}: {e}')
        check_flag = -1
        check_result = {}
        is_complete = False

    # Enrich the entry with check results
    md = dict(entry)
    md['background'] = check_result
    md['is_comp'] = 'yes' if is_complete else 'no'
    md['bg_usable'] = 'yes' if check_flag == 1 else 'no'

    return md, is_complete


def process_all(all_items: list, save_path: str, api_url: str, model_name: str,
                max_new_tokens: int, background_img_dir: str):
    """Process all pending items."""
    done_ids = load_existing_results(save_path)
    todo_items = [item for item in all_items if item['videoid'] not in done_ids]

    print(f'Total: {len(all_items)}, already done: {len(done_ids)}, todo: {len(todo_items)}')

    correct_count = 0
    wrong_count = 0
    skip_count = 0

    for k, entry in enumerate(tqdm(todo_items)):
        videoid = entry['videoid']
        bg_img_path = os.path.join(background_img_dir, f"{videoid}.png")

        now_str = datetime.now().strftime("%H:%M:%S")
        print(f'\n{now_str} [{k}/{len(todo_items)}] Processing: {videoid}')

        # Check if the background image exists before proceeding
        if not os.path.exists(bg_img_path):
            print(f'  Skipping — background image not found')
            skip_count += 1
            continue

        md, is_complete = process_single_item(
            entry, api_url, model_name, max_new_tokens, background_img_dir
        )

        if md is None:
            skip_count += 1
            continue

        # Only save if the check completed without errors
        if is_complete:
            with open(save_path, 'a', encoding='utf8') as f:
                f.write(json.dumps(md, ensure_ascii=False) + '\n')

        if md.get('bg_usable') == 'yes':
            correct_count += 1
        else:
            wrong_count += 1

        total = correct_count + wrong_count
        now_str = datetime.now().strftime("%H:%M:%S")
        print(f'{now_str} [{k}/{len(todo_items)}] '
              f'({total}={correct_count}+{wrong_count}, skip={skip_count}): '
              f'bg_usable={md.get("bg_usable")}')

    print(f'\nDone — correct={correct_count}, wrong={wrong_count}, skipped={skip_count}')


# ────────────────────────── entry point ──────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description="Step6: Background extraction quality check via VLM")
    p.add_argument("--input_json", type=str, required=True,
                   help="Path to the step2 output JSONL file. Each line is a JSON object "
                        "with videoid, image_name, objects (including moving_objects), "
                        "and overall fields")
    p.add_argument("--background_img_dir", type=str, required=True,
                   help="Directory containing background images from step4. "
                        "Images should be named as {videoid}.png")
    p.add_argument("--output", type=str, required=True,
                   help="Path to output JSONL file for saving check results")
    p.add_argument("--server_ip", type=str, required=True, help="VLM server IP address")
    p.add_argument("--server_port", type=str, default="8080",
                   help="VLM server port (default: 8080)")
    p.add_argument("--model_name", type=str, default="Qwen/Qwen3-VL-235B-A22B-Instruct",
                   help="Model name for the VLM API")
    p.add_argument("--max_new_tokens", type=int, default=4096,
                   help="Max new tokens for generation")
    return p.parse_args()


def main():
    args = parse_args()

    # Load input data from step2 output
    all_items = load_input_data(args.input_json)
    print(f'Loaded {len(all_items)} valid items from {args.input_json}')

    # Ensure the output directory exists
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)

    api_url = f'http://{args.server_ip}:{args.server_port}/v1/chat/completions'

    process_all(
        all_items=all_items,
        save_path=args.output,
        api_url=api_url,
        model_name=args.model_name,
        max_new_tokens=args.max_new_tokens,
        background_img_dir=args.background_img_dir,
    )


if __name__ == '__main__':
    main()
