"""
Step5: Subject Extraction Quality Check

This script verifies the quality of subject images extracted by step3. For each
entry from step2's output, it sends the original frame and each extracted subject
image to a VLM server to evaluate:
  1. Whether the extracted subject matches the described object in the original image.
  2. Whether the background is open and whether the subject fits harmoniously.

The subject images are expected to be stored in the directory produced by step3,
following the naming convention: {videoid}_{object_key}_{prompt_id}.png
(This path is NOT stored in the input JSONL; it is derived from --subject_img_dir
combined with the videoid and object keys from each entry.)

Input (--input_json):
    A JSONL file produced by step2. Each line is a JSON object containing:
        - videoid:     unique identifier for the video
        - image_name:  path to the original frame image
        - objects:     dict with "moving_objects" mapping [objectN] -> description
        - overall:     "yes" from step1's self-check
    Only entries with overall == "yes" and non-empty moving_objects are processed.

Input (--subject_img_dir):
    The directory containing subject images generated by step3.
    Images are expected to be named as: {videoid}_{object_key}_{prompt_id}.png

Output (--output):
    A JSONL file where each line is a JSON object with the check results,
    including per-object per-prompt check details and overall usability flags.

Usage:
    python step5.py \\
        --input_json /path/to/step2_output.jsonl \\
        --subject_img_dir /path/to/step3_output/ \\
        --output /path/to/step5_result.jsonl \\
        --server_ip vllm_ip \\
        --server_port vllm_port \\
        --model_name "Qwen/Qwen3-VL-235B-A22B-Instruct"
"""

import json
import os
import io
import base64
import argparse
from datetime import datetime

import requests
from PIL import Image
from tqdm import tqdm


# ────────────────────────── prompts ──────────────────────────

# Check if the extracted subject in the second image matches the object
# in the first image (single-object version)
PROMPT_CHECK_SINGLE = '''
Given the two images, where the second image aims to extract the {text} from the first image as the only subject.

You need to make the following judgments regarding the content of the second image:
1. The second image correctly extracts the described object from the first image.
2. The extracted object is the same physical object as the corresponding one in the first image (Changes in position, pose, orientation, facial expression, and perspective are allowed.).
3. The extracted object, i.e., {text}, is the only main subject in the second image.
4. The extracted object must refer to a complete entity, NOT a partial component or a body part of a subject.
5. If the extracted object is a human character, he or she should appear harmoniously within the second image.

If the second image fully meets the above five requirements, return yes, otherwise return no.

### Output Format:
{{"result":"yes/no"}}
'''

# Check if the extracted subject in the second image matches the object
# in the first image (multi-object version — additionally checks that the
# second image does NOT contain other objects)
PROMPT_CHECK_MULTI = '''
Given the two images, where the second image aims to extract the {text} from the first image as the only subject.

You need to make the following judgments regarding the content of the second image:
1. Whether the second image correctly extracts the described object from the first image.
2. The extracted object is the same physical object as the corresponding one in the first image (Changes in position, pose, orientation, facial expression, and perspective are allowed.).
3. The extracted object, i.e., {text}, is the only main subject in the second image.
4. The second image DOES NOT contain {others} from the first image.
5. The extracted object must refer to a complete entity, NOT a partial component or a body part of a subject.
6. If the extracted object is a human character, he or she should appear harmoniously within the second image.

If the second image fully meets the above six requirements, return yes, otherwise return no.

### Output Format:
{{"result":"yes/no"}}
'''

# Evaluate the background and subject-background fit of the extracted image
PROMPT_META = '''
Given the image, evaluate the following two points and return "yes" or "no":
1. Determine if the image background is an open background. For instance, a plain white clean background is NOT considered an open background. If it is an open background, return "yes" in the "open_background" field; otherwise, return "no".
2. Determine if the main subject is appropriate for the current background. For example, people generally appear more natural in an open background, whereas small products are often clearer and more suitable in a clean background. If the main subject is appropriate for the current background, return "yes" in the "subject_background_fit" field; otherwise, return "no".

Directly output yes or no for each, without any extra explanation.

### Output Format:
{{"open_background":"yes/no", "subject_background_fit":"yes/no"}}
'''

VALID_OBJECT_KEYS = {"[object1]", "[object2]", "[object3]"}

# Number of prompt variants used in step3 (default)
DEFAULT_NUM_PROMPTS = 4


# ────────────────────────── utilities ──────────────────────────

def decode_image(path_or_img, max_side=None) -> str:
    """Read an image file (or accept a PIL Image) and return its base64-encoded string."""
    if isinstance(path_or_img, str):
        im = Image.open(path_or_img).convert("RGB")
    else:
        im = path_or_img.convert("RGB")

    if max_side and max_side > 0:
        w, h = im.size
        scale = max(w, h) / float(max_side)
        if scale > 1:
            im = im.resize((int(round(w / scale)), int(round(h / scale))), Image.BICUBIC)

    buffer = io.BytesIO()
    im.save(buffer, format='JPEG', quality=85)
    return base64.b64encode(buffer.getvalue()).decode()


# ────────────────────────── API helpers ──────────────────────────

def _build_two_image_payload(model_name: str, image_b64_1: str, image_b64_2: str,
                             prompt_text: str, max_new_tokens: int) -> dict:
    """Build the VLM API request payload with two images."""
    return {
        "model": model_name,
        "messages": [{
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_b64_1}"}},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_b64_2}"}},
                {"type": "text", "text": prompt_text},
            ]
        }],
        "max_tokens": max_new_tokens,
    }


def _build_single_image_payload(model_name: str, image_b64: str,
                                prompt_text: str, max_new_tokens: int) -> dict:
    """Build the VLM API request payload with a single image."""
    return {
        "model": model_name,
        "messages": [{
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_b64}"}},
                {"type": "text", "text": prompt_text},
            ]
        }],
        "max_tokens": max_new_tokens,
    }


def send_check_request(url: str, model_name: str, image_b64_1: str, image_b64_2: str,
                       prompt_text: str, max_new_tokens: int, timeout: int = 30):
    """Send a two-image extraction check request. Returns (success, error_msg, content_dict)."""
    payload = _build_two_image_payload(model_name, image_b64_1, image_b64_2,
                                       prompt_text, max_new_tokens)
    for attempt in range(3):
        try:
            resp = requests.post(url, json=payload, timeout=timeout)
            if resp.status_code == 200:
                content = resp.json()["choices"][0]["message"]["content"]
                if '</think>' in content:
                    content = content.split('</think>')[-1].strip()
                content = json.loads(content)
                if content.get("result", "").lower() in ('yes', 'no'):
                    return True, "", content
            else:
                print(f"HTTP {resp.status_code}: {resp.text}")
                if attempt >= 2:
                    return False, f"HTTP {resp.status_code}: {resp.text}", None
        except Exception as e:
            print(e)
            if attempt >= 2:
                return False, str(e), None
    return False, "", None


def send_meta_request(url: str, model_name: str, image_b64: str,
                      prompt_text: str, max_new_tokens: int, timeout: int = 30):
    """Send a single-image metadata check request. Returns (success, error_msg, (open_background, fit))."""
    payload = _build_single_image_payload(model_name, image_b64, prompt_text, max_new_tokens)
    for attempt in range(3):
        try:
            resp = requests.post(url, json=payload, timeout=timeout)
            if resp.status_code == 200:
                content = resp.json()["choices"][0]["message"]["content"]
                if '</think>' in content:
                    content = content.split('</think>')[-1].strip()
                content = json.loads(content)
                bg = content.get("open_background", "").lower()
                fit = content.get("subject_background_fit", "").lower()
                if bg in ('yes', 'no') and fit in ('yes', 'no'):
                    return True, "", (content["open_background"], content["subject_background_fit"])
            else:
                print(f"HTTP {resp.status_code}: {resp.text}")
                if attempt >= 2:
                    return False, f"HTTP {resp.status_code}: {resp.text}", None
        except Exception as e:
            print(e)
            if attempt >= 2:
                return False, str(e), None
    return False, "", None


def check_extracted_image(api_url: str, model_name: str, max_new_tokens: int,
                          original_img, extracted_img_path: str,
                          obj_desc: str, others: str = ""):
    """
    Check the quality of a single extracted subject image.

    Args:
        api_url: VLM API endpoint URL.
        model_name: model name for the API.
        max_new_tokens: max tokens for generation.
        original_img: original frame image (PIL Image).
        extracted_img_path: path to the extracted subject image.
        obj_desc: description of the object to check.
        others: comma-separated descriptions of other objects (for multi-object check).

    Returns:
        (check_flag, check_result, meta_flag, open_background, fit)
        check_flag:  1 = extraction OK, 0 = extraction failed, -1 = error.
        meta_flag:   1 = meta check OK, -1 = error.
    """
    imgb64_1 = decode_image(original_img, 640)
    imgb64_2 = decode_image(extracted_img_path, 640)

    # Choose single or multi-object check prompt
    if not others:
        check_prompt = PROMPT_CHECK_SINGLE.format(text=obj_desc)
    else:
        check_prompt = PROMPT_CHECK_MULTI.format(text=obj_desc, others=others)

    # Check extraction quality
    ok, _, result = send_check_request(api_url, model_name, imgb64_1, imgb64_2,
                                       check_prompt, max_new_tokens)
    if ok:
        check_flag = 1 if result.get('result', 'no').lower() == 'yes' else 0
    else:
        check_flag = -1
        result = {}

    # Check background metadata
    ok2, _, meta_result = send_meta_request(api_url, model_name, imgb64_2,
                                            PROMPT_META, max_new_tokens)
    if ok2:
        meta_flag = 1
        open_bg, fit = meta_result
    else:
        meta_flag = -1
        open_bg, fit = 'unsure', 'unsure'

    return check_flag, result, meta_flag, open_bg, fit


# ────────────────────────── data loading ──────────────────────────

def load_input_data(input_json_path: str) -> list:
    """
    Load valid entries from the step2 output JSONL file.

    Only entries with overall == "yes" and valid, non-empty moving_objects are kept.
    """
    items = []
    with open(input_json_path, 'r', encoding='utf8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue

            if entry.get("overall", "").lower() != "yes":
                continue

            image_path = entry.get('image_name', '')
            if not image_path or not os.path.exists(image_path):
                continue

            try:
                objects = entry['objects']['moving_objects']
            except (KeyError, TypeError):
                continue
            if not objects:
                continue
            if not all(k in VALID_OBJECT_KEYS for k in objects.keys()):
                continue

            items.append(entry)

    return items


def load_existing_results(save_path: str) -> set:
    """Load the set of already-processed videoids from the output file to skip them."""
    if not os.path.exists(save_path):
        return set()

    done_ids = set()
    with open(save_path, 'r', encoding='utf8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
                done_ids.add(item["videoid"])
            except (json.JSONDecodeError, KeyError):
                continue
    return done_ids


def check_all_images_exist(videoid: str, object_keys: list,
                           subject_img_dir: str, num_prompts: int) -> bool:
    """Check if all expected subject images exist for a given entry."""
    for obj_key in object_keys:
        for pid in range(num_prompts):
            img_path = os.path.join(subject_img_dir, f"{videoid}_{obj_key}_{pid}.png")
            if not os.path.exists(img_path):
                return False
    return True


# ────────────────────────── main processing ──────────────────────────

def process_single_item(entry: dict, api_url: str, model_name: str,
                        max_new_tokens: int, subject_img_dir: str,
                        num_prompts: int):
    """
    Process a single entry: check all extracted subject images for quality.

    For each object and each prompt variant, sends the original + extracted image
    to the VLM for verification.

    Returns (result_dict, is_complete):
        result_dict: the entry enriched with check results.
        is_complete: True if all checks completed without errors.
    """
    image_path = entry['image_name']
    videoid = entry['videoid']
    objects = entry['objects']['moving_objects']

    # Open the original image
    try:
        original_img = Image.open(image_path).convert('RGB')
        original_img.thumbnail((640, 640))
    except Exception:
        print(f'  Error opening original image: {image_path}')
        return None, False

    is_complete = True
    is_complete_meta = True
    per_prompt_ok = {pid: True for pid in range(num_prompts)}
    all_objects_usable = True
    all_objects_fit = True

    check_details = {}

    for obj_key in sorted(objects.keys()):
        obj_desc = objects[obj_key]

        # Build "others" string for multi-object check
        others = ""
        if len(objects) > 1:
            others_parts = [objects[k] for k in sorted(objects.keys()) if k != obj_key]
            others = ", ".join(others_parts)

        obj_any_pass = False
        obj_any_fit = False
        per_prompt_results = {}

        for pid in range(num_prompts):
            img_path = os.path.join(subject_img_dir, f"{videoid}_{obj_key}_{pid}.png")

            if not os.path.exists(img_path):
                per_prompt_results[pid] = []
                per_prompt_ok[pid] = False
                continue

            try:
                check_flag, check_result, meta_flag, open_bg, fit = check_extracted_image(
                    api_url, model_name, max_new_tokens,
                    original_img, img_path, obj_desc, others
                )
                check_result['image'] = img_path
                check_result['open_background'] = open_bg
                check_result['fit'] = fit
                per_prompt_results[pid] = [check_result]

                if check_flag == -1:
                    is_complete = False
                if meta_flag == -1:
                    is_complete_meta = False

                now_str = datetime.now().strftime("%H:%M:%S")
                passed = "yes" if check_flag == 1 else "no"
                print(f'  {now_str}: {obj_key} pid={pid} -> {passed}, '
                      f'fit={fit}, bg={open_bg}')

                if check_flag == 1:
                    obj_any_pass = True
                    if fit.lower() == 'yes':
                        obj_any_fit = True

                if check_flag != 1:
                    per_prompt_ok[pid] = False

            except Exception as e:
                print(f'  Error checking {img_path}: {e}')
                per_prompt_results[pid] = []
                is_complete = False
                is_complete_meta = False
                per_prompt_ok[pid] = False

        if not obj_any_pass:
            all_objects_usable = False
        if not obj_any_fit:
            all_objects_fit = False

        check_details[obj_key] = per_prompt_results

    # Enrich the entry with check results
    md = dict(entry)
    md['edited_img'] = check_details
    md['is_comp'] = 'yes' if is_complete else 'no'
    md['is_comp_meta'] = 'yes' if is_complete_meta else 'no'

    for pid in range(num_prompts):
        md[f'is_ok{pid}'] = 'yes' if per_prompt_ok.get(pid, False) else 'no'

    md['usable'] = 'yes' if all_objects_usable else 'no'
    md['usable_with_fit'] = 'yes' if all_objects_fit else 'no'

    return md, is_complete


def process_all(all_items: list, save_path: str, api_url: str, model_name: str,
                max_new_tokens: int, subject_img_dir: str, num_prompts: int):
    """Process all pending items."""
    done_ids = load_existing_results(save_path)
    todo_items = [item for item in all_items if item['videoid'] not in done_ids]

    print(f'Total: {len(all_items)}, already done: {len(done_ids)}, todo: {len(todo_items)}')

    usable_count = 0
    not_usable_count = 0
    skip_count = 0

    for k, entry in enumerate(tqdm(todo_items)):
        videoid = entry['videoid']
        objects = entry['objects']['moving_objects']

        now_str = datetime.now().strftime("%H:%M:%S")
        print(f'\n{now_str} [{k}/{len(todo_items)}] Processing: {videoid}')
        print(f'  objects: {json.dumps(objects)}')

        # Check if all expected images exist before proceeding
        if not check_all_images_exist(videoid, sorted(objects.keys()),
                                      subject_img_dir, num_prompts):
            print(f'  Skipping — not all subject images exist')
            skip_count += 1
            continue

        md, is_complete = process_single_item(
            entry, api_url, model_name, max_new_tokens,
            subject_img_dir, num_prompts
        )

        if md is None:
            skip_count += 1
            continue

        # Only save if all checks completed without errors
        if is_complete:
            with open(save_path, 'a', encoding='utf8') as f:
                f.write(json.dumps(md, ensure_ascii=False) + '\n')

        if md.get('usable') == 'yes':
            usable_count += 1
        else:
            not_usable_count += 1

        total = usable_count + not_usable_count
        now_str = datetime.now().strftime("%H:%M:%S")
        print(f'{now_str} [{k}/{len(todo_items)}] '
              f'({total}={usable_count}+{not_usable_count}, skip={skip_count}): '
              f'usable={md.get("usable")}, usable_with_fit={md.get("usable_with_fit")}')

    print(f'\nDone — usable={usable_count}, not_usable={not_usable_count}, skipped={skip_count}')


# ────────────────────────── entry point ──────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description="Step5: Subject extraction quality check via VLM")
    p.add_argument("--input_json", type=str, required=True,
                   help="Path to the step2 output JSONL file. Each line is a JSON object "
                        "with videoid, image_name, objects (including moving_objects), "
                        "and overall fields")
    p.add_argument("--subject_img_dir", type=str, required=True,
                   help="Directory containing extracted subject images from step3. "
                        "Images should be named as {videoid}_{object_key}_{prompt_id}.png")
    p.add_argument("--output", type=str, required=True,
                   help="Path to output JSONL file for saving check results")
    p.add_argument("--server_ip", type=str, required=True, help="VLM server IP address")
    p.add_argument("--server_port", type=str, default="8080",
                   help="VLM server port (default: 8080)")
    p.add_argument("--model_name", type=str, default="Qwen/Qwen3-VL-235B-A22B-Instruct",
                   help="Model name for the VLM API")
    p.add_argument("--max_new_tokens", type=int, default=4096,
                   help="Max new tokens for generation")
    p.add_argument("--num_prompts", type=int, default=DEFAULT_NUM_PROMPTS,
                   help="Number of prompt variants used in step3 (default: 4)")
    return p.parse_args()


def main():
    args = parse_args()

    # Load input data from step2 output
    all_items = load_input_data(args.input_json)
    print(f'Loaded {len(all_items)} valid items from {args.input_json}')

    # Ensure the output directory exists
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)

    api_url = f'http://{args.server_ip}:{args.server_port}/v1/chat/completions'

    process_all(
        all_items=all_items,
        save_path=args.output,
        api_url=api_url,
        model_name=args.model_name,
        max_new_tokens=args.max_new_tokens,
        subject_img_dir=args.subject_img_dir,
        num_prompts=args.num_prompts,
    )


if __name__ == '__main__':
    main()
